name: build and push to ghcr

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'manifests/**'

env:
  IMAGE_NAME: ghcr.io/unknownblunders/blunders-blog
  PACKAGE_NAME: blunders-blog

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.COMMIT_PAT }}
          submodules: 'true'

# build and push the image to ghcr.io
      - name: Build image
        run: docker build . --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:${{github.sha}}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: docker push $IMAGE_NAME --all-tags

# Update the deployment image tag
# using actions-checkout built in token user https://github.com/actions/checkout#Push-a-commit-using-the-built-in-token
      - name: Update file, then commit and push changes
        run: |
          sed -i 's/ghcr.io\/unknownblunders\/blunders-blog.*/ghcr.io\/unknownblunders\/blunders-blog:${{github.sha}}/g' manifests/deployment.yaml

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add -A
          git commit -m "Update Image tag"
          git push

# by default there's only 500MiB free space on ghcr.io. You can pay for more but I'd like to not pay if possible
      - name: delete old contianers
        uses: actions/delete-package-versions@v4
        with: 
          package-name: ${{ env.PACKAGE_NAME }}
          package-type: 'container'
          token: ${{ secrets.GHCR_PAT }}
          min-versions-to-keep: 2